# Generated by Django 5.2.17 on 2026-09-30 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Level 3 Women's Artistic & Trampoline Coach'",
                        max_length=200,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, verbose_name="Coaching Bio / Background"
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        max_digits=8,
                        verbose_name="Standard Hourly Rate (£/hr or $/hr)",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                (
                    "travel_radius_miles",
                    models.PositiveIntegerField(
                        default=20, verbose_name="Max Travel Radius (miles)"
                    ),
                ),
                (
                    "dbs_checked",
                    models.BooleanField(
                        default=False, verbose_name="DBS / Background Check Verified"
                    ),
                ),
                (
                    "safeguarding_certified",
                    models.BooleanField(
                        default=False,
                        verbose_name="Safeguarding & Child Protection Certified",
                    ),
                ),
                (
                    "first_aid_certified",
                    models.BooleanField(
                        default=False, verbose_name="First Aid Certified"
                    ),
                ),
                (
                    "insurance_valid",
                    models.BooleanField(
                        default=False,
                        verbose_name="Personal / Professional Liability Insurance",
                    ),
                ),
                (
                    "is_available_for_cover",
                    models.BooleanField(
                        default=True, verbose_name="Open for Cover Requests"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        help_text="e.g. Women's Artistic, Men's Artistic, Trampoline, Acrobatic, Pre-School, Tumbling",
                        max_length=150,
                        verbose_name="Discipline / Skill",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Level 1", "Level 1 - Assistant Coach"),
                            ("Level 2", "Level 2 - Lead Coach"),
                            ("Level 3", "Level 3 - Senior Coach"),
                            ("Level 4", "Level 4 - High Performance"),
                            ("Level 5", "Level 5 - Master Coach"),
                            ("Certified", "Standard Certification"),
                        ],
                        default="Level 2",
                        max_length=50,
                    ),
                ),
                (
                    "issuing_body",
                    models.CharField(
                        default="British Gymnastics",
                        max_length=150,
                        verbose_name="Governing Body / Organization",
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="workers.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["discipline", "level"],
            },
        ),
    ]
