# Generated by Django 5.2.17 on 2026-09-30 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("workers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=True,
                        help_text="If true, applies weekly. If false, relies on specific_date.",
                    ),
                ),
                (
                    "specific_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional specific date override",
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="workers.workerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CoverRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'Saturday Morning Advanced WAG Squad'",
                        max_length=200,
                        verbose_name="Class / Session Title",
                    ),
                ),
                ("date", models.DateField(verbose_name="Cover Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "discipline_required",
                    models.CharField(
                        help_text="e.g. Women's Artistic, Trampoline, Pre-School",
                        max_length=150,
                        verbose_name="Discipline Required",
                    ),
                ),
                (
                    "min_level_required",
                    models.CharField(
                        default="Level 2",
                        max_length=50,
                        verbose_name="Minimum Level Required",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        max_digits=8,
                        verbose_name="Offered Hourly Rate (£ or $)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Lesson plans, equipment specifics, emergency contact details",
                        verbose_name="Session Instructions & Notes",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open for Applications"),
                            ("OFFERED", "Offered to Coach"),
                            ("CONFIRMED", "Confirmed / Covered"),
                            ("COMPLETED", "Session Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_covers",
                        to="workers.workerprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_cover_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_requests",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="CoverApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Decision"),
                            ("ACCEPTED", "Accepted / Selected"),
                            ("DECLINED", "Declined"),
                            ("WITHDRAWN", "Withdrawn by Coach"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "pitch_note",
                    models.TextField(
                        blank=True, help_text="Optional note from coach to club"
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cover_applications",
                        to="workers.workerprofile",
                    ),
                ),
                (
                    "cover_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="covers.coverrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cover_request", "worker"),
                        name="unique_cover_application",
                    )
                ],
            },
        ),
    ]
